# fly.toml app configuration file generated for railsdisruptivestudiotest on 2024-01-30T01:21:01-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'railsdisruptivestudiotest'
primary_region = 'qro'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  release_command = './bin/rails db:prepare'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'

[processes]
  web = "/rails/bin/rails fly:server"
  vite = "cd ./client && vite build"  # Define Vite process

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["web"]  # Specify the web process for HTTP service

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["vite"]  # Specify Vite process for HTTP service
